### ISSUE TITLE
🐞 - Editor exceeds container when placed inside flex container

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1325]
### Description

- Place the editor in flex container:
```css
.container {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    align-items: flex-end;
    justify-content: flex-start;
}
```
- Set the editor to only occupy available space:
```css
tui-editor {
    flex: 1 1 0;
    min-height: 100px;
}
```
- This results in the editor exceeding containers height:

![image](https://github.com/user-attachments/assets/a8920930-f9fd-4888-bf7a-b83ddfdf7d56)

### Angular version

18

### Taiga UI version

4

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android
